<?xml version="1.0"?>
<definitions name="Konverzija" targetNamespace="urn:Konverzija" xmlns:tns="urn:Konverzija"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Test">
      <xsd:element name="dataType" type="xsd:integer" />
	  <xsd:element name="konverzijaResponse" type="xsd:string" />	 	  
	</xsd:schema>			
  </types>
  
  <message name="konverzijaEURToBAM">
    <part name="yourValue" type="tns:dataType" />
  </message>
  
  <message name="konverzijaResponse">
    <part name="return" type="tns:dataType" />
  </message>  
  
  <portType name="ConvertPort">
    <operation name="konverzijaEURToBAM">
	  <input message="tns:konverzijaEURToBAM" />
	  <output message="tns:konverzijaResponse" />
	</operation>
  </portType>
  
  <binding name="bind" type="tns:ConvertPort">
	  <operation name="konverzijaEURToBAM">
	    <soap:operation soapAction="urn:ConvertAction" />
		<input>
		  <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />		  
		</input>
		<output>
		  <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />		  
		</output>
	  </operation>
  </binding>
  
  
  
  <service name="Service">
    <port name="ConvertPort" binding="tns:bind">
	  <soap:address location="http://localhost/DZ_003_WSDL_SOAP/konverzijaEURToBAM_server.php"/>
	</port>
  </service>
    
</definitions>