//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZ3_SOAP_WSDL_02.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse HelloWorld(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse> HelloWorldAsync(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSquare", ReplyAction="*")]
        int GetSquare(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSquare", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetSquareAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        float konverzijaBAMToEUR(float bam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaBAMToEURAsync(float bam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        float konverzijaEURToBAM(float eur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaEURToBAMAsync(float eur);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap>, DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap.HelloWorld(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest inValue = new DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest();
            inValue.Body = new DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequestBody();
            DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse retVal = ((DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse> DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap.HelloWorldAsync(DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest inValue = new DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequest();
            inValue.Body = new DZ3_SOAP_WSDL_02.ServiceReference1.HelloWorldRequestBody();
            return ((DZ3_SOAP_WSDL_02.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int GetSquare(int a) {
            return base.Channel.GetSquare(a);
        }
        
        public System.Threading.Tasks.Task<int> GetSquareAsync(int a) {
            return base.Channel.GetSquareAsync(a);
        }
        
        public float konverzijaBAMToEUR(float bam) {
            return base.Channel.konverzijaBAMToEUR(bam);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaBAMToEURAsync(float bam) {
            return base.Channel.konverzijaBAMToEURAsync(bam);
        }
        
        public float konverzijaEURToBAM(float eur) {
            return base.Channel.konverzijaEURToBAM(eur);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaEURToBAMAsync(float eur) {
            return base.Channel.konverzijaEURToBAMAsync(eur);
        }
    }
}
